/* eslint-disable perfectionist/sort-object-types, perfectionist/sort-union-types */
// Generated by scripts/generate-protocol.mjs. Do not edit.
export const PROTOCOL_VERSION = "1.0" as const

/** A bounded, recursively JSON-serializable value. */
export type JsonValue = null | boolean | number | string | ReadonlyArray<JsonValue> | {readonly [key: string]: JsonValue}

/** A bounded JSON object with no non-JSON runtime values. */
export type JsonObject = {readonly [key: string]: JsonValue}

/** The frozen public protocol major/minor identifier. */
export type ProtocolVersion = "1.0"

/** A lowercase SHA-256 digest with an explicit algorithm prefix. */
export type Digest = string

/** An unpadded base64url-encoded Ed25519 signature. */
export type Signature = string

/** SignedRequestMetadata */
export type SignedRequestMetadata = {
	readonly protocolVersion: ProtocolVersion
	readonly deviceId: string
	readonly keyId: string
	readonly requestId: string
	readonly timestamp: string
	readonly nonce: string
	readonly method: "GET" | "POST"
	readonly path: string
	readonly bodyDigest: Digest
	readonly signatureAlgorithm: "ed25519"
	readonly signature: Signature
}

/** ProblemError */
export type ProblemError = {
	readonly pointer: string
	readonly code: string
	readonly detail: string
}

/** Problem */
export type Problem = {
	readonly type: string
	readonly title: string
	readonly status: number
	readonly detail?: string
	readonly instance?: string
	readonly code: string
	readonly retryable: boolean
	readonly traceId?: string
	readonly errors?: ReadonlyArray<ProblemError>
}

/** PublicKey */
export type PublicKey = {
	readonly algorithm: "ed25519"
	readonly keyId: string
	readonly publicKey: string
}

/** ToolDescriptor */
export type ToolDescriptor = {
	readonly name: string
	readonly description: string
	readonly inputSchemaDigest: Digest
	readonly risk: "read" | "write" | "execute" | "network" | "privileged"
	readonly maxResultBytes: number
}

/** DeviceEnrollmentRequest */
export type DeviceEnrollmentRequest = {
	readonly protocolVersion: ProtocolVersion
	readonly enrollmentCode: string
	readonly deviceName: string
	readonly clientVersion: string
	readonly platform: "linux" | "darwin" | "win32"
	readonly devicePublicKey: PublicKey
}

/** TokenSet */
export type TokenSet = {
	readonly tokenType: "Bearer"
	readonly accessToken: string
	readonly accessTokenExpiresAt: string
	readonly refreshToken: string
	readonly refreshTokenExpiresAt: string
}

/** DeviceEnrollmentResponse */
export type DeviceEnrollmentResponse = {
	readonly protocolVersion: ProtocolVersion
	readonly deviceId: string
	readonly tokens: TokenSet
	readonly serverTime: string
	readonly serverSigningKeys: ReadonlyArray<PublicKey>
}

/** DeviceRefreshRequest */
export type DeviceRefreshRequest = {
	readonly protocolVersion: ProtocolVersion
	readonly deviceId: string
	readonly refreshToken: string
	readonly request: SignedRequestMetadata
}

/** DeviceRefreshResponse */
export type DeviceRefreshResponse = {
	readonly protocolVersion: ProtocolVersion
	readonly deviceId: string
	readonly tokens: TokenSet
	readonly serverTime: string
}

/** ClientCapabilities */
export type ClientCapabilities = {
	readonly protocolVersions: ReadonlyArray<ProtocolVersion>
	readonly features: ReadonlyArray<"durable-events" | "event-hash-chain" | "local-tool-execution" | "resumable-sessions" | "digest-bound-approvals" | "sse">
	readonly maxInboundEventBytes: number
	readonly maxOutboundPayloadBytes: number
	readonly tools: ReadonlyArray<ToolDescriptor>
}

/** ServerCapabilities */
export type ServerCapabilities = {
	readonly protocolVersions: ReadonlyArray<ProtocolVersion>
	readonly features: ReadonlyArray<"durable-events" | "event-hash-chain" | "local-tool-execution" | "resumable-sessions" | "digest-bound-approvals" | "sse">
	readonly maxInboundPayloadBytes: number
	readonly maxOutboundEventBytes: number
	readonly heartbeatIntervalMs: number
	readonly eventRetentionSeconds: number
	readonly signingKeys: ReadonlyArray<PublicKey>
}

/** CapabilityNegotiationRequest */
export type CapabilityNegotiationRequest = {
	readonly protocolVersion: ProtocolVersion
	readonly client: ClientCapabilities
	readonly request: SignedRequestMetadata
}

/** NegotiatedCapabilities */
export type NegotiatedCapabilities = {
	readonly protocolVersion: ProtocolVersion
	readonly features: ReadonlyArray<"durable-events" | "event-hash-chain" | "local-tool-execution" | "resumable-sessions" | "digest-bound-approvals" | "sse">
	readonly maxClientPayloadBytes: number
	readonly maxServerEventBytes: number
	readonly heartbeatIntervalMs: number
	readonly eventRetentionSeconds: number
	readonly tools: ReadonlyArray<ToolDescriptor>
}

/** CapabilityNegotiationResponse */
export type CapabilityNegotiationResponse = {
	readonly protocolVersion: ProtocolVersion
	readonly negotiated: NegotiatedCapabilities
	readonly server: ServerCapabilities
	readonly negotiatedAt: string
}

/** ScanRequest */
export type ScanRequest = {
	readonly mode: "audit" | "bounty" | "ci"
	readonly objective: string
	readonly scope: ReadonlyArray<string>
	readonly exclusions: ReadonlyArray<string>
	readonly baselineRevision?: string
	readonly maxDurationSeconds?: number
}

/** RepositoryDescriptor */
export type RepositoryDescriptor = {
	readonly repositoryId: string
	readonly displayName: string
	readonly revision: string
	readonly dirty: boolean
	readonly sourceMode: "tool-mediated"
	readonly semanticIndexDigest: Digest
	readonly repositoryMapDigest: Digest
}

/** CreateSessionRequest */
export type CreateSessionRequest = {
	readonly protocolVersion: ProtocolVersion
	readonly clientRequestId: string
	readonly repository: RepositoryDescriptor
	readonly scan: ScanRequest
	readonly capabilities: NegotiatedCapabilities
	readonly request: SignedRequestMetadata
}

/** UsageTotals */
export type UsageTotals = {
	readonly inputTokens: number
	readonly outputTokens: number
	readonly toolExecutionMilliseconds: number
	readonly storageBytes: number
}

/** SessionSnapshot */
export type SessionSnapshot = {
	readonly protocolVersion: ProtocolVersion
	readonly sessionId: string
	readonly status: "created" | "running" | "paused" | "cancelling" | "cancelled" | "completed" | "failed"
	readonly cursor: number
	readonly createdAt: string
	readonly updatedAt: string
	readonly scan: ScanRequest
	readonly negotiatedCapabilities: NegotiatedCapabilities
	readonly lastEventHash: Digest | null
	readonly pendingToolProposalIds: ReadonlyArray<string>
	readonly usage: UsageTotals
}

/** EventEnvelope */
export type EventEnvelope = {
	readonly protocolVersion: ProtocolVersion
	readonly eventId: string
	readonly sessionId: string
	readonly sequence: number
	readonly occurredAt: string
	readonly eventType: "session.snapshot" | "agent.action" | "tool.proposal" | "execution.grant" | "usage.record" | "session.paused" | "session.resumed" | "session.cancelled" | "session.completed" | "session.failed" | "heartbeat"
	readonly correlationId: string
	readonly causationId: Digest | null
	readonly payload: JsonObject
	readonly payloadDigest: Digest
	readonly previousEventHash: Digest | null
	readonly eventHash: Digest
	readonly signer: PublicKey
	readonly signature: Signature
}

/** ToolProposal */
export type ToolProposal = {
	readonly proposalId: string
	readonly actionId: string
	readonly sessionId: string
	readonly toolName: string
	readonly arguments: JsonObject
	readonly argumentsDigest: Digest
	readonly risk: "read" | "write" | "execute" | "network" | "privileged"
	readonly reason: string
	readonly requestedAt: string
	readonly expiresAt?: string
	readonly idempotencyKey: string
}

/** AgentAction */
export type AgentAction = {
	readonly actionId: string
	readonly sessionId: string
	readonly kind: "analysis" | "propose_tool" | "progress" | "report" | "completed" | "failed"
	readonly summary: string
	readonly toolProposal?: ToolProposal
	readonly data: JsonObject
}

/** ToolDecision */
export type ToolDecision = {
	readonly protocolVersion: ProtocolVersion
	readonly decisionId: string
	readonly sessionId: string
	readonly proposalId: string
	readonly decision: "approve" | "deny"
	readonly decidedAt: string
	readonly actor: "human" | "policy"
	readonly argumentsDigest: Digest
	readonly reason?: string
	readonly constraints?: JsonObject
	readonly request: SignedRequestMetadata
}

/** ExecutionGrant */
export type ExecutionGrant = {
	readonly protocolVersion: ProtocolVersion
	readonly grantId: string
	readonly sessionId: string
	readonly proposalId: string
	readonly decisionId: string
	readonly deviceId: string
	readonly toolName: string
	readonly argumentsDigest: Digest
	readonly decisionDigest: Digest
	readonly issuedAt: string
	readonly expiresAt: string
	readonly nonce: string
	readonly signer: PublicKey
	readonly signature: Signature
}

/** ToolResult */
export type ToolResult = {
	readonly protocolVersion: ProtocolVersion
	readonly resultId: string
	readonly sessionId: string
	readonly proposalId: string
	readonly grantId: string
	readonly grantDigest: Digest
	readonly argumentsDigest: Digest
	readonly startedAt: string
	readonly completedAt: string
	readonly status: "succeeded" | "failed" | "denied" | "cancelled"
	readonly output?: JsonValue
	readonly outputDigest: Digest
	readonly error?: Problem
	readonly truncated: boolean
	readonly originalByteLength: number
	readonly request: SignedRequestMetadata
}

/** UsageRecord */
export type UsageRecord = {
	readonly protocolVersion: ProtocolVersion
	readonly usageId: string
	readonly sessionId: string
	readonly eventId: string
	readonly occurredAt: string
	readonly meter: "input_tokens" | "output_tokens" | "tool_execution_ms" | "storage_bytes"
	readonly quantity: number
	readonly unit: "token" | "millisecond" | "byte"
	readonly billable: boolean
	readonly source: string
	readonly metadata?: JsonObject
}

/** PauseSessionRequest */
export type PauseSessionRequest = {
	readonly protocolVersion: ProtocolVersion
	readonly reason?: string
	readonly request: SignedRequestMetadata
}

/** ResumeSessionRequest */
export type ResumeSessionRequest = {
	readonly protocolVersion: ProtocolVersion
	readonly cursor: number
	readonly lastEventHash: Digest | null
	readonly request: SignedRequestMetadata
}

/** CancelSessionRequest */
export type CancelSessionRequest = {
	readonly protocolVersion: ProtocolVersion
	readonly reason?: string
	readonly request: SignedRequestMetadata
}

/** SessionControlResponse */
export type SessionControlResponse = {
	readonly protocolVersion: ProtocolVersion
	readonly sessionId: string
	readonly status: "running" | "paused" | "cancelling" | "cancelled"
	readonly effectiveAt: string
	readonly cursor: number
}

/** HealthResponse */
export type HealthResponse = {
	readonly status: "ok" | "degraded"
	readonly protocolVersion: ProtocolVersion
	readonly serverTime: string
}

/** ReadinessCheck */
export type ReadinessCheck = {
	readonly name: string
	readonly status: "ready" | "not_ready"
	readonly detail: string
}

/** ReadinessResponse */
export type ReadinessResponse = {
	readonly status: "ready" | "not_ready"
	readonly protocolVersion: ProtocolVersion
	readonly serverTime: string
	readonly checks: ReadonlyArray<ReadinessCheck>
}
