/**
 * Bounty Report Generator - Deterministic JSON-to-Markdown Templating Engine.
 *
 * THE LLM IS NEVER ALLOWED TO WRITE THE FINAL REPORT PROSE.
 *
 * It produces structured JSON data only. This module renders that data
 * into fixed Markdown templates, injecting raw sandbox execution logs
 * verbatim as cryptographic proof. The LLM cannot exaggerate, hallucinate,
 * or embellish the proof-of-concept section.
 */

import { type OastCallback, type SandboxExecResult } from '../dast/dast-schema.js';

// =============================================================================
// Types
// =============================================================================

export interface BountyFindingData {
  cweId: string;
  impactDescription: string;
  remediationSummary?: string;
  reproductionSteps: string[];
  severityLabel: string;
  summary: string;
  title: string;
  vulnId: string;
}

export interface BountyReportOptions {
  findings: BountyFindingData[];
  oastCallbacks?: OastCallback[];
  platform?: 'bugcrowd' | 'generic' | 'hackerone';
  sandboxLogs?: SandboxExecResult[];
  targetName: string;
}

// =============================================================================
// CWE / OWASP Link Helpers
// =============================================================================

function cweUrl(cweId: string): string {
  const num = cweId.replace(/^CWE-?/i, '');
  return `https://cwe.mitre.org/data/definitions/${num}.html`;
}

function owaspLink(cweId: string): string | undefined {
  const num = Number.parseInt(cweId.replace(/^CWE-?/i, ''), 10);

  // Map common CWEs to OWASP Top 10
  const map: Record<number, string> = {
    22: 'https://owasp.org/Top10/A01_2021-Broken_Access_Control/',
    78: 'https://owasp.org/Top10/A03_2021-Injection/',
    79: 'https://owasp.org/Top10/A03_2021-Injection/',
    89: 'https://owasp.org/Top10/A03_2021-Injection/',
    94: 'https://owasp.org/Top10/A03_2021-Injection/',
    200: 'https://owasp.org/Top10/A01_2021-Broken_Access_Control/',
    287: 'https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/',
    327: 'https://owasp.org/Top10/A02_2021-Cryptographic_Failures/',
    502: 'https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/',
    611: 'https://owasp.org/Top10/A05_2021-Security_Misconfiguration/',
    918: 'https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery/',
  };

  return map[num];
}

// =============================================================================
// Platform Headers
// =============================================================================

function platformHeader(platform: string, targetName: string): string {
  switch (platform) {
    case 'bugcrowd': {
      return [
        `# Security Assessment Report — ${targetName}`,
        `> Platform: Bugcrowd`,
        `> Generated by: Shadow Auditor (Autonomous)`,
        `> Date: ${new Date().toISOString().split('T')[0]}`,
        '',
      ].join('\n');
    }

    case 'hackerone': {
      return [
        `# Security Assessment Report — ${targetName}`,
        `> Platform: HackerOne`,
        `> Generated by: Shadow Auditor (Autonomous)`,
        `> Date: ${new Date().toISOString().split('T')[0]}`,
        '',
      ].join('\n');
    }

    default: {
      return [
        `# Security Assessment Report — ${targetName}`,
        `> Generated by: Shadow Auditor (Autonomous)`,
        `> Date: ${new Date().toISOString().split('T')[0]}`,
        '',
      ].join('\n');
    }
  }
}

// =============================================================================
// Per-Finding Template
// =============================================================================

/**
 * Generate a deterministic Markdown report for a single finding.
 *
 * The "Proof of Concept" section is populated EXCLUSIVELY from raw
 * SandboxExecResult logs. The LLM has no access to modify this section.
 */
export function generatePerFindingReport(
  finding: BountyFindingData,
  sandboxLogs: SandboxExecResult[],
  oastCallbacks: OastCallback[],
): string {
  const sections: string[] = [];
  const cweNum = finding.cweId.replace(/^CWE-?/i, '');

  // Header
  sections.push(`## [CWE-${cweNum}] ${finding.title}`, '', `**Severity:** ${finding.severityLabel} | **ID:** ${finding.vulnId}`, '', '### Summary', finding.summary, '', '### Steps to Reproduce');
  for (const [i, step] of finding.reproductionSteps.entries()) {
    sections.push(`${i + 1}. ${step}`);
  }

  sections.push('');

  // Proof of Concept (VERBATIM from sandbox logs — NEVER LLM-generated)
  if (sandboxLogs.length > 0) {
    sections.push('### Proof of Concept', '', '> ⚠️ The following commands and outputs were captured verbatim from', '> an isolated sandbox execution. They have NOT been modified by AI.', '');

    for (const log of sandboxLogs) {
      sections.push('```bash', `$ ${log.command}`);
      if (log.stdout.trim()) {
        sections.push(log.stdout.trim());
      }

      if (log.stderr.trim()) {
        sections.push(`# stderr:`, log.stderr.trim());
      }

      sections.push(`# exit code: ${log.exitCode} | duration: ${log.durationMs}ms`, '```', '');
    }
  }

  // OAST Callback Evidence
  if (oastCallbacks.length > 0) {
    sections.push('### OAST Callback Evidence', '', '| Timestamp | URL | Method |', '|-----------|-----|--------|');

    for (const cb of oastCallbacks) {
      sections.push(`| ${cb.timestamp} | \`${cb.url}\` | ${cb.method} |`);
    }

    sections.push('');
  }

  // Impact
  sections.push('### Impact', finding.impactDescription, '');

  // Suggested Remediation
  if (finding.remediationSummary) {
    sections.push('### Suggested Remediation', finding.remediationSummary, '');
  }

  // References
  sections.push('### References', `- ${cweUrl(finding.cweId)}`);

  const owasp = owaspLink(finding.cweId);
  if (owasp) {
    sections.push(`- ${owasp}`);
  }

  sections.push('');

  return sections.join('\n');
}

// =============================================================================
// Full Report Generator
// =============================================================================

/**
 * Generate a complete bounty report from structured finding data.
 *
 * This is the main entry point for the deterministic report generator.
 * It does NOT call any LLM — it templates pure data into Markdown.
 */
export function generateBountyReport(options: BountyReportOptions): string {
  const { findings, oastCallbacks = [], platform = 'generic', sandboxLogs = [], targetName } = options;

  const sections: string[] = [];

  // Platform header
  sections.push(platformHeader(platform, targetName), '## Executive Summary', '', `Shadow Auditor identified **${findings.length}** security finding(s) in **${targetName}**.`, '');

  // Severity breakdown
  const severityCounts: Record<string, number> = {};
  for (const f of findings) {
    severityCounts[f.severityLabel] = (severityCounts[f.severityLabel] ?? 0) + 1;
  }

  sections.push('| Severity | Count |', '|----------|-------|');

  for (const [severity, count] of Object.entries(severityCounts).sort()) {
    sections.push(`| ${severity} | ${count} |`);
  }

  sections.push('', '## Table of Contents', '');

  for (const f of findings) {
    const cweNum = f.cweId.replace(/^CWE-?/i, '');
    sections.push(`- [CWE-${cweNum}] ${f.title}`);
  }

  sections.push('', '---', '');

  // Individual findings
  for (const finding of findings) {
    // Match sandbox logs and OAST callbacks to this finding
    const matchedLogs = sandboxLogs.filter((log) =>
      log.command.includes(finding.vulnId) ||
      log.stdout.includes(finding.vulnId) ||
      log.stderr.includes(finding.vulnId),
    );

    const matchedCallbacks = oastCallbacks.filter((cb) =>
      cb.url.includes(finding.vulnId),
    );

    // Fall back to all logs if no specific match
    const logsForFinding = matchedLogs.length > 0 ? matchedLogs : sandboxLogs;
    const callbacksForFinding = matchedCallbacks.length > 0 ? matchedCallbacks : oastCallbacks;

    sections.push(generatePerFindingReport(finding, logsForFinding, callbacksForFinding), '---', '');
  }

  // Footer
  sections.push('---', `*Report generated by Shadow Auditor on ${new Date().toISOString()}*`, '');

  return sections.join('\n');
}

// =============================================================================
// Index Generator
// =============================================================================

/**
 * Generate an index file linking all per-finding reports.
 */
export function generateFindingsIndex(
  findings: BountyFindingData[],
  targetName: string,
): string {
  const lines: string[] = [];

  lines.push(`# Security Findings — ${targetName}`, '', `> ${findings.length} finding(s) identified by Shadow Auditor`, '', '| ID | Severity | Title | CWE |', '|----|----------|-------|-----|');

  for (const f of findings) {
    const cweNum = f.cweId.replace(/^CWE-?/i, '');
    const filename = `${f.vulnId}.md`;
    lines.push(`| [${f.vulnId}](${filename}) | ${f.severityLabel} | ${f.title} | CWE-${cweNum} |`);
  }

  lines.push('');

  return lines.join('\n');
}
