/**
 * Swarm Coordinator - Parallel multi-agent task and execution manager.
 *
 * The coordinator now drives execution through a LangGraph supervisor graph
 * backed by PersistentCheckpointSaver. The imperative while(true) loop has been
 * replaced by checkpointed graph nodes, so orchestration state survives process
 * restarts.
 */

import { type LanguageModel, type ToolSet } from 'ai';

import { type ShadowConfig } from '../../utils/config.js';
import { PersistentCheckpointSaver } from '../orchestrator/checkpoint-saver.js';
import { AgentWorker } from './agent-worker.js';
import { Blackboard } from './blackboard.js';
import { type AgentRole, type BlackboardState } from './hivemind-schema.js';
import {
  resolveWorkerModel,
  resolveWorkerTier,
  type SwarmModelOverrides,
} from './swarm-model-router.js';
import { buildSwarmSupervisor, type SwarmCoordinatorRuntime } from './swarm-supervisor.js';

export interface SwarmCoordinatorOptions {
  allTools: ToolSet;
  auditMode?: string;
  /** Optional existing blackboard to reuse across missions */
  blackboard?: Blackboard;
  config: ShadowConfig;
  diffScopeHint?: string;
  model: LanguageModel;
  runId: string;
  storagePath: string;
}

/**
 * Manages swarm orchestration, task dependency decomposition, parallel execution, and consensus flow.
 */
export class SwarmCoordinator implements SwarmCoordinatorRuntime {
  public readonly allTools: ToolSet;
  public readonly auditMode: string;
  public readonly config: ShadowConfig;
  public readonly diffScopeHint: string;
  public readonly model: LanguageModel;
  onActivity?: (
    workerRole: AgentRole,
    activity: { kind: string; message: string; toolName?: string },
  ) => void;
  public readonly runId: string;
public readonly storagePath: string;
  private blackboard: Blackboard | null = null;
  private userMessage = '';
private readonly workers: Map<string, AgentWorker> = new Map();

  constructor(options: SwarmCoordinatorOptions) {
    this.config = options.config;
    this.model = options.model;
    this.allTools = options.allTools;
    this.storagePath = options.storagePath;
    this.runId = options.runId;
    this.auditMode = options.auditMode ?? 'sast';
    this.diffScopeHint = options.diffScopeHint ?? '';
    this.blackboard = options.blackboard ?? null;
  }

  createWorker(options: {
    agentId: string;
    model: LanguageModel;
    modelTier: ReturnType<typeof resolveWorkerTier>['modelTier'];
    role: AgentRole;
    trustScore: number;
  }): AgentWorker {
    return new AgentWorker({
      agentId: options.agentId,
      allTools: this.allTools,
      auditMode: this.auditMode,
      blackboard: this.getBlackboard(),
      diffScopeHint: this.diffScopeHint,
      maxOutputTokens: 4096,
      maxToolSteps: 10,
      model: options.model,
      modelTier: options.modelTier,
      role: options.role,
      trustScore: options.trustScore,
    });
  }

  async executeMission(
    userMessage: string,
    onActivity?: (
      workerRole: AgentRole,
      activity: { kind: string; message: string; toolName?: string },
    ) => void,
  ): Promise<string> {
    this.userMessage = userMessage;
    this.onActivity = onActivity;

    // 1. Initialize Blackboard (reuse existing if provided for cross-mission persistence)
    if (!this.blackboard) {
      this.blackboard = await Blackboard.create({
        heartbeatTimeout: 60_000,
        runId: this.runId,
        storagePath: this.storagePath,
      });
    }

    const blackboard = this.blackboard;

    // 2. Build the checkpointed LangGraph supervisor.
    const checkpointer = new PersistentCheckpointSaver({ storagePath: this.storagePath });
    await checkpointer.initialize();

    const supervisor = buildSwarmSupervisor({
      blackboard,
      checkpointer,
      coordinator: this,
    });

    // 3. Run the graph. Resuming from a checkpoint is automatic when the same
    //    thread_id/run_id is reused.
    const finalState = await supervisor.invoke(
      {},
      { configurable: { thread_id: this.runId } },
    );

    // 4. Extract the final report from the reporter task result.
    const finalBlackboard = (finalState as { blackboard?: BlackboardState }).blackboard ?? {
      tasks: [],
    };
    const reportTask = finalBlackboard.tasks.find((t) => t.taskType === 'report');
    const reporterOutput = typeof reportTask?.result === 'string' ? reportTask.result : '';

    return reporterOutput || 'No report generated by reporting worker.';
  }

  findIdleWorker(role: AgentRole, blackboard: Blackboard, excludedWorkers?: Set<string>): AgentWorker | undefined {
    return [...this.workers.values()].find((w) => {
      if (excludedWorkers?.has(w.agentId)) return false;
      const active = blackboard.getActiveAgents().find((a) => a.agentId === w.agentId);
      return w.role === role && active?.status === 'idle';
    });
  }

  getBlackboard(): Blackboard {
    if (!this.blackboard) {
      throw new Error('Blackboard has not been initialized');
    }

    return this.blackboard;
  }

  getConfig(): ShadowConfig {
    return this.config;
  }

  getModel(): LanguageModel {
    return this.model;
  }

  getOnActivity(): SwarmCoordinatorRuntime['onActivity'] | undefined {
    return this.onActivity;
  }

  getUserMessage(): string {
    return this.userMessage;
  }

  isPatchEnabled(): boolean {
    return this.config.swarm?.roles?.includes('patch-engineer') ?? false;
  }

  registerWorker(agentId: string, worker: AgentWorker): void {
    this.workers.set(agentId, worker);
  }

  terminateAllWorkers(): void {
    for (const worker of this.workers.values()) {
      worker.terminate();
    }
  }
}
